import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={dmSans.className}>
      <body className="antialiased">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
